# Form implementation generated from reading ui file 'playersActivityPanel.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_playersactivitypanel(object):
    def setupUi(self, playersactivitypanel):
        playersactivitypanel.setObjectName("playersactivitypanel")
        playersactivitypanel.resize(711, 161)
        font = QtGui.QFont()
        font.setPointSize(12)
        playersactivitypanel.setFont(font)
        self.playersactivitywidget = QtWidgets.QWidget(parent=playersactivitypanel)
        self.playersactivitywidget.setGeometry(QtCore.QRect(0, 0, 711, 161))
        self.playersactivitywidget.setObjectName("playersactivitywidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.playersactivitywidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 12, 311, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.playersF2ActivityLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.playersF2ActivityLabel.setObjectName("playersF2ActivityLabel")
        self.verticalLayout_2.addWidget(self.playersF2ActivityLabel)
        self.playersF3ActivityLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.playersF3ActivityLabel.setObjectName("playersF3ActivityLabel")
        self.verticalLayout_2.addWidget(self.playersF3ActivityLabel)
        self.playersDoubleClickActivityLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.playersDoubleClickActivityLabel.setObjectName("playersDoubleClickActivityLabel")
        self.verticalLayout_2.addWidget(self.playersDoubleClickActivityLabel)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=self.playersactivitywidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(390, 10, 311, 141))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.playersF9ActivityLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.playersF9ActivityLabel.setObjectName("playersF9ActivityLabel")
        self.verticalLayout_6.addWidget(self.playersF9ActivityLabel)
        self.playersF10ActivityLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.playersF10ActivityLabel.setObjectName("playersF10ActivityLabel")
        self.verticalLayout_6.addWidget(self.playersF10ActivityLabel)
        self.playersEscActivityLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.playersEscActivityLabel.setObjectName("playersEscActivityLabel")
        self.verticalLayout_6.addWidget(self.playersEscActivityLabel)

        self.retranslateUi(playersactivitypanel)
        QtCore.QMetaObject.connectSlotsByName(playersactivitypanel)

    def retranslateUi(self, playersactivitypanel):
        _translate = QtCore.QCoreApplication.translate
        playersactivitypanel.setWindowTitle(_translate("playersactivitypanel", "Cribbage Grass Roots"))
        self.playersF2ActivityLabel.setText(_translate("playersactivitypanel", "F2    Edit player selected in listbox"))
        self.playersF3ActivityLabel.setText(_translate("playersactivitypanel", "F3    Create a new player"))
        self.playersDoubleClickActivityLabel.setText(_translate("playersactivitypanel", "Double Click entry to toggle active status"))
        self.playersF9ActivityLabel.setText(_translate("playersactivitypanel", "F9    Toggle active status for selected player"))
        self.playersF10ActivityLabel.setText(_translate("playersactivitypanel", "F10  Save all current changes"))
        self.playersEscActivityLabel.setText(_translate("playersactivitypanel", "Esc   Quit current activity"))
