# Form implementation generated from reading ui file 'reportsActivityPanel.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_reportsactivitypanel(object):
    def setupUi(self, reportsactivitypanel):
        reportsactivitypanel.setObjectName("reportsactivitypanel")
        reportsactivitypanel.resize(711, 161)
        font = QtGui.QFont()
        font.setPointSize(12)
        reportsactivitypanel.setFont(font)
        self.reportsactivitywidget = QtWidgets.QWidget(parent=reportsactivitypanel)
        self.reportsactivitywidget.setGeometry(QtCore.QRect(0, 0, 711, 161))
        self.reportsactivitywidget.setObjectName("reportsactivitywidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.reportsactivitywidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 3, 301, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.reportsPickTourneyActivityLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.reportsPickTourneyActivityLabel.setObjectName("reportsPickTourneyActivityLabel")
        self.verticalLayout.addWidget(self.reportsPickTourneyActivityLabel)
        self.reportsSelectReportsActivityLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.reportsSelectReportsActivityLabel.setObjectName("reportsSelectReportsActivityLabel")
        self.verticalLayout.addWidget(self.reportsSelectReportsActivityLabel)
        self.reportsRunReportsActivityLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.reportsRunReportsActivityLabel.setObjectName("reportsRunReportsActivityLabel")
        self.verticalLayout.addWidget(self.reportsRunReportsActivityLabel)

        self.retranslateUi(reportsactivitypanel)
        QtCore.QMetaObject.connectSlotsByName(reportsactivitypanel)

    def retranslateUi(self, reportsactivitypanel):
        _translate = QtCore.QCoreApplication.translate
        reportsactivitypanel.setWindowTitle(_translate("reportsactivitypanel", "Cribbage Grass Roots"))
        self.reportsPickTourneyActivityLabel.setText(_translate("reportsactivitypanel", "First Pick a Tourney"))
        self.reportsSelectReportsActivityLabel.setText(_translate("reportsactivitypanel", "Then Select One or More Reports"))
        self.reportsRunReportsActivityLabel.setText(_translate("reportsactivitypanel", "Then Press Run Reports"))
