# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'CribbageQteqRfew.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QLabel,
    QLayout, QLineEdit, QListWidget, QListWidgetItem,
    QMainWindow, QPushButton, QSizePolicy, QStackedWidget,
    QTabWidget, QVBoxLayout, QWidget)

class Ui_MainCribbageWindow(object):
    def setupUi(self, MainCribbageWindow):
        if not MainCribbageWindow.objectName():
            MainCribbageWindow.setObjectName(u"MainCribbageWindow")
        MainCribbageWindow.resize(1156, 915)
        font = QFont()
        font.setPointSize(12)
        font.setWeight(QFont.Medium)
        MainCribbageWindow.setFont(font)
        self.TopContainer = QWidget(MainCribbageWindow)
        self.TopContainer.setObjectName(u"TopContainer")
        self.sessionPanel = QFrame(self.TopContainer)
        self.sessionPanel.setObjectName(u"sessionPanel")
        self.sessionPanel.setGeometry(QRect(10, 20, 1091, 201))
        self.sessionPanel.setFrameShape(QFrame.Shape.Box)
        self.sessionPanel.setFrameShadow(QFrame.Shadow.Raised)
        self.sessionPanel.setLineWidth(3)
        self.fr_clubPanel = QFrame(self.sessionPanel)
        self.fr_clubPanel.setObjectName(u"fr_clubPanel")
        self.fr_clubPanel.setGeometry(QRect(20, 20, 301, 171))
        self.fr_clubPanel.setFrameShape(QFrame.Shape.Box)
        self.fr_clubPanel.setFrameShadow(QFrame.Shadow.Sunken)
        self.fr_clubPanel.setLineWidth(2)
        self.label_8 = QLabel(self.fr_clubPanel)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 20, 63, 20))
        self.label_8.setFrameShape(QFrame.Shape.Panel)
        self.label_8.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_8.setLineWidth(2)
        self.label_17 = QLabel(self.fr_clubPanel)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 95, 61, 21))
        self.label_17.setFrameShape(QFrame.Shape.Panel)
        self.label_17.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_17.setLineWidth(2)
        self.label_18 = QLabel(self.fr_clubPanel)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 60, 63, 20))
        self.label_18.setFrameShape(QFrame.Shape.Panel)
        self.label_18.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_18.setLineWidth(2)
        self.label_19 = QLabel(self.fr_clubPanel)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 130, 61, 20))
        self.label_19.setFrameShape(QFrame.Shape.Panel)
        self.label_19.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_19.setLineWidth(2)
        self.hdrClubNumber = QLabel(self.fr_clubPanel)
        self.hdrClubNumber.setObjectName(u"hdrClubNumber")
        self.hdrClubNumber.setGeometry(QRect(80, 20, 31, 20))
        self.hdrClubNumber.setAutoFillBackground(False)
        self.hdrClubNumber.setStyleSheet(u"color: rgb(85, 0, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.hdrClubNumber.setFrameShape(QFrame.Shape.Panel)
        self.hdrClubNumber.setFrameShadow(QFrame.Shadow.Sunken)
        self.hdrClubNumber.setLineWidth(2)
        self.hdrClubNumber.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.hdrClubName = QLabel(self.fr_clubPanel)
        self.hdrClubName.setObjectName(u"hdrClubName")
        self.hdrClubName.setGeometry(QRect(80, 60, 141, 20))
        self.hdrClubName.setStyleSheet(u"color: rgb(85, 0, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.hdrClubName.setFrameShape(QFrame.Shape.Panel)
        self.hdrClubName.setFrameShadow(QFrame.Shadow.Sunken)
        self.hdrClubName.setLineWidth(2)
        self.hdrActivePlayerCount = QLabel(self.fr_clubPanel)
        self.hdrActivePlayerCount.setObjectName(u"hdrActivePlayerCount")
        self.hdrActivePlayerCount.setGeometry(QRect(80, 95, 31, 20))
        self.hdrActivePlayerCount.setStyleSheet(u"color: rgb(85, 0, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.hdrActivePlayerCount.setFrameShape(QFrame.Shape.Panel)
        self.hdrActivePlayerCount.setFrameShadow(QFrame.Shadow.Sunken)
        self.hdrActivePlayerCount.setLineWidth(2)
        self.hdrActivePlayerCount.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.hdrSeason = QLabel(self.fr_clubPanel)
        self.hdrSeason.setObjectName(u"hdrSeason")
        self.hdrSeason.setGeometry(QRect(80, 130, 71, 20))
        self.hdrSeason.setStyleSheet(u"color: rgb(85, 0, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.hdrSeason.setFrameShape(QFrame.Shape.Panel)
        self.hdrSeason.setFrameShadow(QFrame.Shadow.Sunken)
        self.hdrSeason.setLineWidth(2)
        self.fr_activityPanel = QFrame(self.sessionPanel)
        self.fr_activityPanel.setObjectName(u"fr_activityPanel")
        self.fr_activityPanel.setGeometry(QRect(340, 20, 741, 171))
        self.fr_activityPanel.setFrameShape(QFrame.Shape.Box)
        self.fr_activityPanel.setFrameShadow(QFrame.Shadow.Sunken)
        self.fr_activityPanel.setLineWidth(2)
        self.stackedActivityWidget = QStackedWidget(self.fr_activityPanel)
        self.stackedActivityWidget.setObjectName(u"stackedActivityWidget")
        self.stackedActivityWidget.setGeometry(QRect(11, 10, 731, 161))
        self.playersActivityPage = QWidget()
        self.playersActivityPage.setObjectName(u"playersActivityPage")
        self.stackedActivityWidget.addWidget(self.playersActivityPage)
        self.tourneysActivityPage = QWidget()
        self.tourneysActivityPage.setObjectName(u"tourneysActivityPage")
        self.stackedActivityWidget.addWidget(self.tourneysActivityPage)
        self.reportsActivityPage = QWidget()
        self.reportsActivityPage.setObjectName(u"reportsActivityPage")
        self.stackedActivityWidget.addWidget(self.reportsActivityPage)
        self.resultsActivityPage = QWidget()
        self.resultsActivityPage.setObjectName(u"resultsActivityPage")
        self.stackedActivityWidget.addWidget(self.resultsActivityPage)
        self.clubFrameLabel = QLabel(self.sessionPanel)
        self.clubFrameLabel.setObjectName(u"clubFrameLabel")
        self.clubFrameLabel.setGeometry(QRect(26, 10, 41, 20))
        self.clubFrameLabel.setAutoFillBackground(True)
        self.clubFrameLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.activityFrameLabel = QLabel(self.sessionPanel)
        self.activityFrameLabel.setObjectName(u"activityFrameLabel")
        self.activityFrameLabel.setGeometry(QRect(350, 10, 63, 20))
        self.activityFrameLabel.setAutoFillBackground(True)
        self.activityFrameLabel.setStyleSheet(u"opacity: 1.0;")
        self.activityFrameLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.SessionFrameLabel = QLabel(self.TopContainer)
        self.SessionFrameLabel.setObjectName(u"SessionFrameLabel")
        self.SessionFrameLabel.setGeometry(QRect(20, 10, 63, 20))
        self.SessionFrameLabel.setFont(font)
        self.SessionFrameLabel.setAutoFillBackground(True)
        self.SessionFrameLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.tabWidget = QTabWidget(self.TopContainer)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 220, 1101, 691))
        self.playersTab = QWidget()
        self.playersTab.setObjectName(u"playersTab")
        self.playersTab.setAutoFillBackground(True)
        self.playerTabPanel = QFrame(self.playersTab)
        self.playerTabPanel.setObjectName(u"playerTabPanel")
        self.playerTabPanel.setGeometry(QRect(10, 0, 1071, 641))
        self.playerTabPanel.setAutoFillBackground(True)
        self.playerTabPanel.setFrameShape(QFrame.Shape.Panel)
        self.playerTabPanel.setFrameShadow(QFrame.Shadow.Sunken)
        self.playerTabPanel.setLineWidth(2)
        self.newPlayerFrame = QFrame(self.playerTabPanel)
        self.newPlayerFrame.setObjectName(u"newPlayerFrame")
        self.newPlayerFrame.setGeometry(QRect(420, 80, 451, 511))
        self.newPlayerFrame.setAutoFillBackground(True)
        self.newPlayerFrame.setFrameShape(QFrame.Shape.Panel)
        self.newPlayerFrame.setFrameShadow(QFrame.Shadow.Sunken)
        self.newPlayerFrame.setLineWidth(2)
        self.lb_newPlayerLabel = QLabel(self.newPlayerFrame)
        self.lb_newPlayerLabel.setObjectName(u"lb_newPlayerLabel")
        self.lb_newPlayerLabel.setGeometry(QRect(100, 10, 191, 20))
        self.layoutWidget = QWidget(self.newPlayerFrame)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(30, 50, 111, 451))
        self.verticalLayout = QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.firstNameLabel = QLabel(self.layoutWidget)
        self.firstNameLabel.setObjectName(u"firstNameLabel")
        self.firstNameLabel.setEnabled(True)
        self.firstNameLabel.setAutoFillBackground(True)
        self.firstNameLabel.setScaledContents(False)

        self.verticalLayout.addWidget(self.firstNameLabel)

        self.lastNameLabel = QLabel(self.layoutWidget)
        self.lastNameLabel.setObjectName(u"lastNameLabel")

        self.verticalLayout.addWidget(self.lastNameLabel)

        self.streetLabel = QLabel(self.layoutWidget)
        self.streetLabel.setObjectName(u"streetLabel")

        self.verticalLayout.addWidget(self.streetLabel)

        self.cityLabel = QLabel(self.layoutWidget)
        self.cityLabel.setObjectName(u"cityLabel")

        self.verticalLayout.addWidget(self.cityLabel)

        self.stateLabel = QLabel(self.layoutWidget)
        self.stateLabel.setObjectName(u"stateLabel")

        self.verticalLayout.addWidget(self.stateLabel)

        self.zipLabel = QLabel(self.layoutWidget)
        self.zipLabel.setObjectName(u"zipLabel")

        self.verticalLayout.addWidget(self.zipLabel)

        self.phoneLabel = QLabel(self.layoutWidget)
        self.phoneLabel.setObjectName(u"phoneLabel")

        self.verticalLayout.addWidget(self.phoneLabel)

        self.emailLabel = QLabel(self.layoutWidget)
        self.emailLabel.setObjectName(u"emailLabel")

        self.verticalLayout.addWidget(self.emailLabel)

        self.accNumberLabel = QLabel(self.layoutWidget)
        self.accNumberLabel.setObjectName(u"accNumberLabel")

        self.verticalLayout.addWidget(self.accNumberLabel)

        self.expiresLabel = QLabel(self.layoutWidget)
        self.expiresLabel.setObjectName(u"expiresLabel")

        self.verticalLayout.addWidget(self.expiresLabel)

        self.joinedLabel = QLabel(self.layoutWidget)
        self.joinedLabel.setObjectName(u"joinedLabel")

        self.verticalLayout.addWidget(self.joinedLabel)

        self.activeLabel = QLabel(self.layoutWidget)
        self.activeLabel.setObjectName(u"activeLabel")
        self.activeLabel.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.verticalLayout.addWidget(self.activeLabel)

        self.label = QLabel(self.newPlayerFrame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(330, 479, 71, 21))
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.existingPlayersPanel = QFrame(self.playerTabPanel)
        self.existingPlayersPanel.setObjectName(u"existingPlayersPanel")
        self.existingPlayersPanel.setGeometry(QRect(30, 10, 341, 631))
        self.existingPlayersPanel.setAutoFillBackground(True)
        self.existingPlayersPanel.setFrameShape(QFrame.Shape.Panel)
        self.existingPlayersPanel.setFrameShadow(QFrame.Shadow.Sunken)
        self.existingPlayersPanel.setLineWidth(2)
        self.existingPlayersLabel = QLabel(self.existingPlayersPanel)
        self.existingPlayersLabel.setObjectName(u"existingPlayersLabel")
        self.existingPlayersLabel.setGeometry(QRect(40, 10, 211, 20))
        self.activePlayerLabel = QLabel(self.existingPlayersPanel)
        self.activePlayerLabel.setObjectName(u"activePlayerLabel")
        self.activePlayerLabel.setGeometry(QRect(40, 50, 81, 20))
        self.showAllPlayers = QCheckBox(self.existingPlayersPanel)
        self.showAllPlayers.setObjectName(u"showAllPlayers")
        self.showAllPlayers.setGeometry(QRect(140, 50, 87, 24))
        self.listOfPlayers = QListWidget(self.existingPlayersPanel)
        self.listOfPlayers.setObjectName(u"listOfPlayers")
        self.listOfPlayers.setGeometry(QRect(30, 80, 231, 541))
        self.listOfPlayers.setFrameShape(QFrame.Shape.Box)
        self.listOfPlayers.setLineWidth(3)
        self.listOfPlayers.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.listOfPlayers.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.listOfPlayers.setSelectionRectVisible(True)
        self.listOfPlayers.setSortingEnabled(False)
        self.layoutWidget1 = QWidget(self.playerTabPanel)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(570, 130, 152, 461))
        self.verticalLayout_2 = QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setSizeConstraint(QLayout.SizeConstraint.SetNoConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.le_firstNameEntry = QLineEdit(self.layoutWidget1)
        self.le_firstNameEntry.setObjectName(u"le_firstNameEntry")

        self.verticalLayout_2.addWidget(self.le_firstNameEntry)

        self.le_lastNameEntry = QLineEdit(self.layoutWidget1)
        self.le_lastNameEntry.setObjectName(u"le_lastNameEntry")

        self.verticalLayout_2.addWidget(self.le_lastNameEntry)

        self.le_streetEntry = QLineEdit(self.layoutWidget1)
        self.le_streetEntry.setObjectName(u"le_streetEntry")

        self.verticalLayout_2.addWidget(self.le_streetEntry)

        self.le_cityEntry = QLineEdit(self.layoutWidget1)
        self.le_cityEntry.setObjectName(u"le_cityEntry")

        self.verticalLayout_2.addWidget(self.le_cityEntry)

        self.le_stateEntry = QLineEdit(self.layoutWidget1)
        self.le_stateEntry.setObjectName(u"le_stateEntry")

        self.verticalLayout_2.addWidget(self.le_stateEntry)

        self.le_zipEntry = QLineEdit(self.layoutWidget1)
        self.le_zipEntry.setObjectName(u"le_zipEntry")

        self.verticalLayout_2.addWidget(self.le_zipEntry)

        self.le_phoneEntry = QLineEdit(self.layoutWidget1)
        self.le_phoneEntry.setObjectName(u"le_phoneEntry")

        self.verticalLayout_2.addWidget(self.le_phoneEntry)

        self.le_emailEntry = QLineEdit(self.layoutWidget1)
        self.le_emailEntry.setObjectName(u"le_emailEntry")

        self.verticalLayout_2.addWidget(self.le_emailEntry)

        self.le_accNumberEntry = QLineEdit(self.layoutWidget1)
        self.le_accNumberEntry.setObjectName(u"le_accNumberEntry")

        self.verticalLayout_2.addWidget(self.le_accNumberEntry)

        self.le_expiresEntry = QLineEdit(self.layoutWidget1)
        self.le_expiresEntry.setObjectName(u"le_expiresEntry")

        self.verticalLayout_2.addWidget(self.le_expiresEntry)

        self.le_joinedEntry = QLineEdit(self.layoutWidget1)
        self.le_joinedEntry.setObjectName(u"le_joinedEntry")

        self.verticalLayout_2.addWidget(self.le_joinedEntry)

        self.le_activeEntry = QLineEdit(self.layoutWidget1)
        self.le_activeEntry.setObjectName(u"le_activeEntry")

        self.verticalLayout_2.addWidget(self.le_activeEntry)

        self.tabWidget.addTab(self.playersTab, "")
        self.tourneysTab = QWidget()
        self.tourneysTab.setObjectName(u"tourneysTab")
        self.tourneysTab.setAutoFillBackground(True)
        self.tourneysTabPanel = QFrame(self.tourneysTab)
        self.tourneysTabPanel.setObjectName(u"tourneysTabPanel")
        self.tourneysTabPanel.setGeometry(QRect(10, 10, 1041, 641))
        self.tourneysTabPanel.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.tourneysTabPanel.setAutoFillBackground(True)
        self.tourneysTabPanel.setFrameShape(QFrame.Shape.Box)
        self.tourneysTabPanel.setFrameShadow(QFrame.Shadow.Sunken)
        self.tourneysTabPanel.setLineWidth(2)
        self.TourneysFrame = QFrame(self.tourneysTabPanel)
        self.TourneysFrame.setObjectName(u"TourneysFrame")
        self.TourneysFrame.setGeometry(QRect(10, 10, 1021, 631))
        self.TourneysFrame.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.TourneysFrame.setAutoFillBackground(True)
        self.TourneysFrame.setFrameShape(QFrame.Shape.Panel)
        self.TourneysFrame.setFrameShadow(QFrame.Shadow.Sunken)
        self.TourneysFrame.setLineWidth(2)
        self.F6TourneyFrame = QFrame(self.TourneysFrame)
        self.F6TourneyFrame.setObjectName(u"F6TourneyFrame")
        self.F6TourneyFrame.setGeometry(QRect(10, 20, 381, 61))
        self.F6TourneyFrame.setAutoFillBackground(True)
        self.F6TourneyFrame.setFrameShape(QFrame.Shape.Panel)
        self.F6TourneyFrame.setFrameShadow(QFrame.Shadow.Sunken)
        self.F6TourneyFrame.setLineWidth(2)
        self.tourneyF6EnterResultsLabel = QLabel(self.F6TourneyFrame)
        self.tourneyF6EnterResultsLabel.setObjectName(u"tourneyF6EnterResultsLabel")
        self.tourneyF6EnterResultsLabel.setGeometry(QRect(10, 10, 351, 31))
        font1 = QFont()
        font1.setPointSize(14)
        font1.setBold(True)
        self.tourneyF6EnterResultsLabel.setFont(font1)
        self.tourneyF6EnterResultsLabel.setStyleSheet(u"\n"
"color: rgb(65, 161, 5);")
        self.tourneyF6EnterResultsLabel.setLineWidth(-5)
        self.ExistingTourneysPanel = QFrame(self.TourneysFrame)
        self.ExistingTourneysPanel.setObjectName(u"ExistingTourneysPanel")
        self.ExistingTourneysPanel.setGeometry(QRect(10, 91, 261, 541))
        self.ExistingTourneysPanel.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.ExistingTourneysPanel.setAutoFillBackground(True)
        self.ExistingTourneysPanel.setFrameShape(QFrame.Shape.Box)
        self.ExistingTourneysPanel.setFrameShadow(QFrame.Shadow.Sunken)
        self.ExistingTourneysPanel.setLineWidth(2)
        self.trnyNoHdr = QLabel(self.ExistingTourneysPanel)
        self.trnyNoHdr.setObjectName(u"trnyNoHdr")
        self.trnyNoHdr.setGeometry(QRect(10, 30, 41, 41))
        self.trnyNoHdr.setWordWrap(True)
        self.trnyDataHdr = QLabel(self.ExistingTourneysPanel)
        self.trnyDataHdr.setObjectName(u"trnyDataHdr")
        self.trnyDataHdr.setGeometry(QRect(60, 50, 41, 20))
        self.trnyDateHdr = QLabel(self.ExistingTourneysPanel)
        self.trnyDateHdr.setObjectName(u"trnyDateHdr")
        self.trnyDateHdr.setGeometry(QRect(140, 30, 41, 41))
        self.trnyDateHdr.setWordWrap(True)
        self.label_4 = QLabel(self.TourneysFrame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 82, 151, 20))
        self.label_4.setAutoFillBackground(True)
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lw_listOfTourneys = QListWidget(self.TourneysFrame)
        self.lw_listOfTourneys.setObjectName(u"lw_listOfTourneys")
        self.lw_listOfTourneys.setGeometry(QRect(10, 170, 231, 461))
        self.lw_listOfTourneys.setFrameShape(QFrame.Shape.Box)
        self.lw_listOfTourneys.setLineWidth(2)
        self.NewTourneyPanel = QFrame(self.TourneysFrame)
        self.NewTourneyPanel.setObjectName(u"NewTourneyPanel")
        self.NewTourneyPanel.setGeometry(QRect(420, 170, 341, 101))
        self.NewTourneyPanel.setAutoFillBackground(True)
        self.NewTourneyPanel.setFrameShape(QFrame.Shape.Panel)
        self.NewTourneyPanel.setFrameShadow(QFrame.Shadow.Sunken)
        self.NewTourneyPanel.setLineWidth(2)
        self.lb_tourneyNumberLabel = QLabel(self.NewTourneyPanel)
        self.lb_tourneyNumberLabel.setObjectName(u"lb_tourneyNumberLabel")
        self.lb_tourneyNumberLabel.setGeometry(QRect(10, 30, 161, 20))
        self.lb_tourneyDateLabel = QLabel(self.NewTourneyPanel)
        self.lb_tourneyDateLabel.setObjectName(u"lb_tourneyDateLabel")
        self.lb_tourneyDateLabel.setGeometry(QRect(10, 60, 151, 20))
        self.le_tourneyNumberEntry = QLineEdit(self.NewTourneyPanel)
        self.le_tourneyNumberEntry.setObjectName(u"le_tourneyNumberEntry")
        self.le_tourneyNumberEntry.setGeometry(QRect(180, 30, 51, 26))
        self.le_tourneyDateEntry = QLineEdit(self.NewTourneyPanel)
        self.le_tourneyDateEntry.setObjectName(u"le_tourneyDateEntry")
        self.le_tourneyDateEntry.setGeometry(QRect(180, 60, 141, 26))
        self.newTourneyFrameLabel = QLabel(self.TourneysFrame)
        self.newTourneyFrameLabel.setObjectName(u"newTourneyFrameLabel")
        self.newTourneyFrameLabel.setGeometry(QRect(430, 160, 101, 20))
        self.newTourneyFrameLabel.setAutoFillBackground(True)
        self.newTourneyFrameLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.frame = QFrame(self.TourneysFrame)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(415, 310, 351, 181))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.lb_badNumber = QLabel(self.frame)
        self.lb_badNumber.setObjectName(u"lb_badNumber")

        self.verticalLayout_3.addWidget(self.lb_badNumber)

        self.lb_tourneyOutofRange = QLabel(self.frame)
        self.lb_tourneyOutofRange.setObjectName(u"lb_tourneyOutofRange")

        self.verticalLayout_3.addWidget(self.lb_tourneyOutofRange)

        self.lb_duplicateTourneyNumber = QLabel(self.frame)
        self.lb_duplicateTourneyNumber.setObjectName(u"lb_duplicateTourneyNumber")

        self.verticalLayout_3.addWidget(self.lb_duplicateTourneyNumber)

        self.lb_badDateFormat = QLabel(self.frame)
        self.lb_badDateFormat.setObjectName(u"lb_badDateFormat")

        self.verticalLayout_3.addWidget(self.lb_badDateFormat)

        self.lb_duplicateTourneyDate = QLabel(self.frame)
        self.lb_duplicateTourneyDate.setObjectName(u"lb_duplicateTourneyDate")

        self.verticalLayout_3.addWidget(self.lb_duplicateTourneyDate)

        self.F6TourneyFrame.raise_()
        self.ExistingTourneysPanel.raise_()
        self.label_4.raise_()
        self.NewTourneyPanel.raise_()
        self.lw_listOfTourneys.raise_()
        self.newTourneyFrameLabel.raise_()
        self.frame.raise_()
        self.label_2 = QLabel(self.tourneysTabPanel)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 0, 63, 20))
        self.label_2.setAutoFillBackground(True)
        self.tabWidget.addTab(self.tourneysTab, "")
        self.resultsTab = QWidget()
        self.resultsTab.setObjectName(u"resultsTab")
        self.resultsTab.setAutoFillBackground(True)
        self.resultsTabPanel = QFrame(self.resultsTab)
        self.resultsTabPanel.setObjectName(u"resultsTabPanel")
        self.resultsTabPanel.setGeometry(QRect(10, 10, 1071, 641))
        self.resultsTabPanel.setAutoFillBackground(True)
        self.resultsTabPanel.setFrameShape(QFrame.Shape.StyledPanel)
        self.resultsTabPanel.setFrameShadow(QFrame.Shadow.Raised)
        self.fr_resultsPanel = QFrame(self.resultsTabPanel)
        self.fr_resultsPanel.setObjectName(u"fr_resultsPanel")
        self.fr_resultsPanel.setGeometry(QRect(0, 0, 1091, 631))
        self.fr_resultsPanel.setAutoFillBackground(True)
        self.fr_resultsPanel.setFrameShape(QFrame.Shape.Panel)
        self.fr_resultsPanel.setFrameShadow(QFrame.Shadow.Sunken)
        self.fr_resultsPanel.setLineWidth(2)
        self.fr_resultsHdrPanel = QFrame(self.fr_resultsPanel)
        self.fr_resultsHdrPanel.setObjectName(u"fr_resultsHdrPanel")
        self.fr_resultsHdrPanel.setGeometry(QRect(20, 20, 241, 91))
        self.fr_resultsHdrPanel.setAutoFillBackground(True)
        self.fr_resultsHdrPanel.setFrameShape(QFrame.Shape.Panel)
        self.fr_resultsHdrPanel.setFrameShadow(QFrame.Shadow.Raised)
        self.fr_resultsHdrPanel.setLineWidth(2)
        self.label_9 = QLabel(self.fr_resultsHdrPanel)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 10, 101, 20))
        self.label_10 = QLabel(self.fr_resultsHdrPanel)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 36, 91, 20))
        self.label_11 = QLabel(self.fr_resultsHdrPanel)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 60, 63, 20))
        self.lb_tourneyHdrDate = QLabel(self.fr_resultsHdrPanel)
        self.lb_tourneyHdrDate.setObjectName(u"lb_tourneyHdrDate")
        self.lb_tourneyHdrDate.setGeometry(QRect(130, 10, 91, 20))
        self.lb_tourneyHdrDate.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lb_tourneyHdrNumber = QLabel(self.fr_resultsHdrPanel)
        self.lb_tourneyHdrNumber.setObjectName(u"lb_tourneyHdrNumber")
        self.lb_tourneyHdrNumber.setGeometry(QRect(131, 35, 31, 20))
        self.lb_tourneyHdrNumber.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lb_tourneyHdrCount = QLabel(self.fr_resultsHdrPanel)
        self.lb_tourneyHdrCount.setObjectName(u"lb_tourneyHdrCount")
        self.lb_tourneyHdrCount.setGeometry(QRect(130, 60, 31, 20))
        self.lb_tourneyHdrCount.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fr_resultsTracking = QFrame(self.fr_resultsPanel)
        self.fr_resultsTracking.setObjectName(u"fr_resultsTracking")
        self.fr_resultsTracking.setGeometry(QRect(300, 20, 261, 91))
        self.fr_resultsTracking.setFrameShape(QFrame.Shape.Panel)
        self.fr_resultsTracking.setFrameShadow(QFrame.Shadow.Raised)
        self.fr_resultsTracking.setLineWidth(2)
        self.label_12 = QLabel(self.fr_resultsTracking)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 30, 63, 20))
        self.label_13 = QLabel(self.fr_resultsTracking)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 60, 63, 20))
        self.label_14 = QLabel(self.fr_resultsTracking)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(90, 10, 31, 20))
        self.label_15 = QLabel(self.fr_resultsTracking)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(141, 10, 51, 20))
        self.label_16 = QLabel(self.fr_resultsTracking)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(210, 10, 31, 20))
        self.lb_spreadPlusValue = QLabel(self.fr_resultsTracking)
        self.lb_spreadPlusValue.setObjectName(u"lb_spreadPlusValue")
        self.lb_spreadPlusValue.setGeometry(QRect(88, 33, 41, 20))
        self.lb_spreadPlusValue.setStyleSheet(u"\n"
"background-color: rgb(187, 255, 215)\n"
"")
        self.lb_spreadPlusValue.setFrameShape(QFrame.Shape.StyledPanel)
        self.lb_spreadMinusValue = QLabel(self.fr_resultsTracking)
        self.lb_spreadMinusValue.setObjectName(u"lb_spreadMinusValue")
        self.lb_spreadMinusValue.setGeometry(QRect(145, 34, 41, 20))
        self.lb_spreadMinusValue.setStyleSheet(u"background-color: rgb(255, 211, 205);")
        self.lb_spreadMinusValue.setFrameShape(QFrame.Shape.StyledPanel)
        self.lb_spreadDiffValue = QLabel(self.fr_resultsTracking)
        self.lb_spreadDiffValue.setObjectName(u"lb_spreadDiffValue")
        self.lb_spreadDiffValue.setGeometry(QRect(210, 35, 31, 20))
        self.lb_spreadDiffValue.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lb_spreadDiffValue.setFrameShape(QFrame.Shape.StyledPanel)
        self.lb_skunkPlusValue = QLabel(self.fr_resultsTracking)
        self.lb_skunkPlusValue.setObjectName(u"lb_skunkPlusValue")
        self.lb_skunkPlusValue.setGeometry(QRect(88, 58, 41, 20))
        self.lb_skunkPlusValue.setStyleSheet(u"background-color: rgb(187, 255, 215);")
        self.lb_skunkPlusValue.setFrameShape(QFrame.Shape.StyledPanel)
        self.lb_skunkMinusValue = QLabel(self.fr_resultsTracking)
        self.lb_skunkMinusValue.setObjectName(u"lb_skunkMinusValue")
        self.lb_skunkMinusValue.setGeometry(QRect(146, 59, 41, 20))
        self.lb_skunkMinusValue.setStyleSheet(u"background-color: rgb(255, 211, 205);")
        self.lb_skunkMinusValue.setFrameShape(QFrame.Shape.StyledPanel)
        self.lb_skunkDiffValue = QLabel(self.fr_resultsTracking)
        self.lb_skunkDiffValue.setObjectName(u"lb_skunkDiffValue")
        self.lb_skunkDiffValue.setGeometry(QRect(210, 58, 31, 20))
        self.lb_skunkDiffValue.setStyleSheet(u"\n"
"background-color: rgb(255, 255, 255);")
        self.lb_skunkDiffValue.setFrameShape(QFrame.Shape.StyledPanel)
        self.fr_selectedPlayersPanel = QFrame(self.fr_resultsPanel)
        self.fr_selectedPlayersPanel.setObjectName(u"fr_selectedPlayersPanel")
        self.fr_selectedPlayersPanel.setGeometry(QRect(20, 130, 241, 491))
        self.fr_selectedPlayersPanel.setAutoFillBackground(True)
        self.fr_selectedPlayersPanel.setFrameShape(QFrame.Shape.Panel)
        self.fr_selectedPlayersPanel.setFrameShadow(QFrame.Shadow.Raised)
        self.fr_selectedPlayersPanel.setLineWidth(2)
        self.label_7 = QLabel(self.fr_selectedPlayersPanel)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 10, 41, 20))
        self.listOfPlayerNames = QLabel(self.fr_selectedPlayersPanel)
        self.listOfPlayerNames.setObjectName(u"listOfPlayerNames")
        self.listOfPlayerNames.setGeometry(QRect(60, 10, 91, 20))
        self.lw_listOfPlayersPoints = QListWidget(self.fr_selectedPlayersPanel)
        self.lw_listOfPlayersPoints.setObjectName(u"lw_listOfPlayersPoints")
        self.lw_listOfPlayersPoints.setGeometry(QRect(10, 30, 31, 451))
        self.lw_listOfResultPlayers = QListWidget(self.fr_selectedPlayersPanel)
        self.lw_listOfResultPlayers.setObjectName(u"lw_listOfResultPlayers")
        self.lw_listOfResultPlayers.setGeometry(QRect(60, 30, 151, 451))
        self.fr_tourneyResultsPanel = QFrame(self.fr_resultsPanel)
        self.fr_tourneyResultsPanel.setObjectName(u"fr_tourneyResultsPanel")
        self.fr_tourneyResultsPanel.setGeometry(QRect(300, 130, 541, 491))
        self.fr_tourneyResultsPanel.setAutoFillBackground(True)
        self.fr_tourneyResultsPanel.setFrameShape(QFrame.Shape.Panel)
        self.fr_tourneyResultsPanel.setFrameShadow(QFrame.Shadow.Raised)
        self.fr_tourneyResultsPanel.setLineWidth(2)
        self.lw_listOfResultsNames = QListWidget(self.fr_tourneyResultsPanel)
        self.lw_listOfResultsNames.setObjectName(u"lw_listOfResultsNames")
        self.lw_listOfResultsNames.setGeometry(QRect(10, 30, 161, 451))
        self.lw_listOfResultsNames.setFrameShape(QFrame.Shape.Panel)
        self.lw_listOfResultsNames.setLineWidth(3)
        self.label_23 = QLabel(self.fr_tourneyResultsPanel)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(60, 6, 63, 20))
        font2 = QFont()
        font2.setFamilies([u"Calibri"])
        font2.setPointSize(12)
        font2.setBold(True)
        self.label_23.setFont(font2)
        self.label_23.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_24 = QLabel(self.fr_tourneyResultsPanel)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(193, 10, 21, 20))
        self.label_24.setFont(font2)
        self.label_25 = QLabel(self.fr_tourneyResultsPanel)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(228, 10, 31, 20))
        self.label_25.setFont(font2)
        self.label_26 = QLabel(self.fr_tourneyResultsPanel)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(274, 10, 41, 20))
        self.label_26.setFont(font2)
        self.label_27 = QLabel(self.fr_tourneyResultsPanel)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(325, 10, 31, 20))
        self.label_27.setFont(font2)
        self.label_28 = QLabel(self.fr_tourneyResultsPanel)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(450, 10, 41, 20))
        self.label_28.setFont(font2)
        self.label_29 = QLabel(self.fr_tourneyResultsPanel)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(414, 10, 31, 20))
        self.label_29.setFont(font2)
        self.label_31 = QLabel(self.fr_tourneyResultsPanel)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(373, 10, 21, 20))
        self.label_31.setFont(font2)
        self.lw_listOfResultsGp = QListWidget(self.fr_tourneyResultsPanel)
        self.lw_listOfResultsGp.setObjectName(u"lw_listOfResultsGp")
        self.lw_listOfResultsGp.setGeometry(QRect(180, 30, 41, 451))
        self.lw_listOfResultsGp.setFrameShape(QFrame.Shape.Box)
        self.lw_listOfResultsGp.setFrameShadow(QFrame.Shadow.Raised)
        self.lw_listOfResultsGp.setLineWidth(2)
        self.lw_listOfResultsGw = QListWidget(self.fr_tourneyResultsPanel)
        self.lw_listOfResultsGw.setObjectName(u"lw_listOfResultsGw")
        self.lw_listOfResultsGw.setGeometry(QRect(220, 30, 41, 451))
        self.lw_listOfResultsGw.setFrameShape(QFrame.Shape.Box)
        self.lw_listOfResultsGw.setFrameShadow(QFrame.Shadow.Raised)
        self.lw_listOfResultsGw.setLineWidth(2)
        self.lw_listOfResultsSprd = QListWidget(self.fr_tourneyResultsPanel)
        self.lw_listOfResultsSprd.setObjectName(u"lw_listOfResultsSprd")
        self.lw_listOfResultsSprd.setGeometry(QRect(260, 30, 61, 451))
        self.lw_listOfResultsSprd.setFrameShape(QFrame.Shape.Box)
        self.lw_listOfResultsSprd.setFrameShadow(QFrame.Shadow.Raised)
        self.lw_listOfResultsSprd.setLineWidth(2)
        self.lw_listOfResultsTkn = QListWidget(self.fr_tourneyResultsPanel)
        self.lw_listOfResultsTkn.setObjectName(u"lw_listOfResultsTkn")
        self.lw_listOfResultsTkn.setGeometry(QRect(320, 30, 41, 451))
        self.lw_listOfResultsTkn.setFrameShape(QFrame.Shape.Box)
        self.lw_listOfResultsTkn.setFrameShadow(QFrame.Shadow.Raised)
        self.lw_listOfResultsTkn.setLineWidth(2)
        self.lw_listOfResultsCash = QListWidget(self.fr_tourneyResultsPanel)
        self.lw_listOfResultsCash.setObjectName(u"lw_listOfResultsCash")
        self.lw_listOfResultsCash.setGeometry(QRect(360, 30, 51, 451))
        self.lw_listOfResultsCash.setFrameShape(QFrame.Shape.Box)
        self.lw_listOfResultsCash.setFrameShadow(QFrame.Shadow.Raised)
        self.lw_listOfResultsCash.setLineWidth(2)
        self.lw_listOfResultsGvn = QListWidget(self.fr_tourneyResultsPanel)
        self.lw_listOfResultsGvn.setObjectName(u"lw_listOfResultsGvn")
        self.lw_listOfResultsGvn.setGeometry(QRect(410, 30, 41, 451))
        self.lw_listOfResultsGvn.setFrameShape(QFrame.Shape.Box)
        self.lw_listOfResultsGvn.setFrameShadow(QFrame.Shadow.Raised)
        self.lw_listOfResultsGvn.setLineWidth(2)
        self.lw_listOfResultsOrder = QListWidget(self.fr_tourneyResultsPanel)
        self.lw_listOfResultsOrder.setObjectName(u"lw_listOfResultsOrder")
        self.lw_listOfResultsOrder.setGeometry(QRect(450, 30, 41, 451))
        self.lw_listOfResultsOrder.setFrameShape(QFrame.Shape.Box)
        self.lw_listOfResultsOrder.setFrameShadow(QFrame.Shadow.Raised)
        self.lw_listOfResultsOrder.setLineWidth(2)
        self.label_5 = QLabel(self.fr_resultsPanel)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 120, 121, 20))
        self.label_5.setAutoFillBackground(True)
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_6 = QLabel(self.fr_resultsPanel)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(400, 120, 121, 20))
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_41 = QLabel(self.fr_resultsPanel)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(580, 34, 141, 20))
        self.label_41.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_42 = QLabel(self.fr_resultsPanel)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(743, 34, 31, 20))
        self.label_43 = QLabel(self.fr_resultsPanel)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(790, 34, 31, 20))
        self.label_44 = QLabel(self.fr_resultsPanel)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(844, 34, 51, 20))
        self.label_45 = QLabel(self.fr_resultsPanel)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(905, 34, 31, 20))
        self.label_46 = QLabel(self.fr_resultsPanel)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(955, 34, 31, 20))
        self.label_47 = QLabel(self.fr_resultsPanel)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(992, 34, 41, 20))
        self.label_47.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.fr_resultLine = QFrame(self.fr_resultsPanel)
        self.fr_resultLine.setObjectName(u"fr_resultLine")
        self.fr_resultLine.setGeometry(QRect(590, 60, 471, 41))
        self.fr_resultLine.setFrameShape(QFrame.Shape.StyledPanel)
        self.fr_resultLine.setFrameShadow(QFrame.Shadow.Raised)
        self.label_40 = QLabel(self.fr_resultLine)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(380, 10, 31, 20))
        self.le_resultLinePlayerTkn = QLineEdit(self.fr_resultLine)
        self.le_resultLinePlayerTkn.setObjectName(u"le_resultLinePlayerTkn")
        self.le_resultLinePlayerTkn.setGeometry(QRect(310, 10, 41, 21))
        self.le_resultLinePlayerTkn.setAutoFillBackground(True)
        self.le_resultLinePlayerCash = QLineEdit(self.fr_resultLine)
        self.le_resultLinePlayerCash.setObjectName(u"le_resultLinePlayerCash")
        self.le_resultLinePlayerCash.setGeometry(QRect(360, 10, 41, 21))
        self.le_resultLinePlayerCash.setAutoFillBackground(True)
        self.le_resultLinePlayerSprd = QLineEdit(self.fr_resultLine)
        self.le_resultLinePlayerSprd.setObjectName(u"le_resultLinePlayerSprd")
        self.le_resultLinePlayerSprd.setGeometry(QRect(243, 10, 60, 21))
        self.le_resultLinePlayerSprd.setAutoFillBackground(True)
        self.lb_resultLinePlayerName = QLabel(self.fr_resultLine)
        self.lb_resultLinePlayerName.setObjectName(u"lb_resultLinePlayerName")
        self.lb_resultLinePlayerName.setGeometry(QRect(0, 10, 141, 21))
        font3 = QFont()
        font3.setPointSize(12)
        font3.setBold(True)
        self.lb_resultLinePlayerName.setFont(font3)
        self.lb_resultLinePlayerName.setStyleSheet(u"color: rgb(122, 122, 122)")
        self.lb_resultLinePlayerName.setFrameShape(QFrame.Shape.StyledPanel)
        self.le_resultLinePlayerGw = QLineEdit(self.fr_resultLine)
        self.le_resultLinePlayerGw.setObjectName(u"le_resultLinePlayerGw")
        self.le_resultLinePlayerGw.setGeometry(QRect(195, 10, 41, 21))
        self.le_resultLinePlayerGw.setAcceptDrops(False)
        self.le_resultLinePlayerGw.setAutoFillBackground(True)
        self.lb_resultLinePlayerGvn = QLabel(self.fr_resultLine)
        self.lb_resultLinePlayerGvn.setObjectName(u"lb_resultLinePlayerGvn")
        self.lb_resultLinePlayerGvn.setGeometry(QRect(410, 10, 31, 20))
        self.lb_resultLinePlayerGvn.setAutoFillBackground(False)
        self.lb_resultLinePlayerGvn.setStyleSheet(u"background-color: rgb(187, 255, 215)")
        self.lb_resultLinePlayerGvn.setFrameShape(QFrame.Shape.StyledPanel)
        self.le_resultLinePlayerGp = QLineEdit(self.fr_resultLine)
        self.le_resultLinePlayerGp.setObjectName(u"le_resultLinePlayerGp")
        self.le_resultLinePlayerGp.setGeometry(QRect(148, 10, 41, 21))
        self.label_3 = QLabel(self.resultsTabPanel)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 0, 91, 20))
        self.label_3.setAutoFillBackground(True)
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.tabWidget.addTab(self.resultsTab, "")
        self.reportsTab = QWidget()
        self.reportsTab.setObjectName(u"reportsTab")
        self.reportsTab.setAutoFillBackground(True)
        self.reportsTabPanel = QFrame(self.reportsTab)
        self.reportsTabPanel.setObjectName(u"reportsTabPanel")
        self.reportsTabPanel.setGeometry(QRect(10, 10, 1081, 651))
        self.reportsTabPanel.setAutoFillBackground(False)
        self.reportsTabPanel.setFrameShape(QFrame.Shape.Panel)
        self.reportsTabPanel.setFrameShadow(QFrame.Shadow.Sunken)
        self.reportsTabPanel.setLineWidth(2)
        self.tourneysPanel = QFrame(self.reportsTabPanel)
        self.tourneysPanel.setObjectName(u"tourneysPanel")
        self.tourneysPanel.setGeometry(QRect(10, 0, 201, 621))
        self.tourneysPanel.setAutoFillBackground(True)
        self.tourneysPanel.setFrameShape(QFrame.Shape.Panel)
        self.tourneysPanel.setFrameShadow(QFrame.Shadow.Sunken)
        self.tourneysPanel.setLineWidth(3)
        self.lw_listOfReportTourneys = QListWidget(self.tourneysPanel)
        self.lw_listOfReportTourneys.setObjectName(u"lw_listOfReportTourneys")
        self.lw_listOfReportTourneys.setGeometry(QRect(10, 20, 151, 571))
        self.reportButtonsPanel = QFrame(self.reportsTabPanel)
        self.reportButtonsPanel.setObjectName(u"reportButtonsPanel")
        self.reportButtonsPanel.setGeometry(QRect(210, 0, 231, 621))
        self.reportButtonsPanel.setAutoFillBackground(True)
        self.reportButtonsPanel.setFrameShape(QFrame.Shape.Panel)
        self.reportButtonsPanel.setFrameShadow(QFrame.Shadow.Sunken)
        self.reportButtonsPanel.setLineWidth(3)
        self.ckb_allReports = QCheckBox(self.reportButtonsPanel)
        self.ckb_allReports.setObjectName(u"ckb_allReports")
        self.ckb_allReports.setGeometry(QRect(30, 70, 101, 24))
        self.ckb_allReports.setChecked(False)
        self.ckb_alpha = QCheckBox(self.reportButtonsPanel)
        self.ckb_alpha.setObjectName(u"ckb_alpha")
        self.ckb_alpha.setGeometry(QRect(30, 150, 121, 24))
        self.ckb_battingAverage = QCheckBox(self.reportButtonsPanel)
        self.ckb_battingAverage.setObjectName(u"ckb_battingAverage")
        self.ckb_battingAverage.setGeometry(QRect(30, 190, 191, 24))
        self.ckb_cash = QCheckBox(self.reportButtonsPanel)
        self.ckb_cash.setObjectName(u"ckb_cash")
        self.ckb_cash.setGeometry(QRect(30, 230, 131, 24))
        self.ckb_individStats = QCheckBox(self.reportButtonsPanel)
        self.ckb_individStats.setObjectName(u"ckb_individStats")
        self.ckb_individStats.setGeometry(QRect(30, 270, 161, 24))
        self.ckb_nationalAvges = QCheckBox(self.reportButtonsPanel)
        self.ckb_nationalAvges.setObjectName(u"ckb_nationalAvges")
        self.ckb_nationalAvges.setGeometry(QRect(30, 310, 181, 24))
        self.ckb_qtrDrop = QCheckBox(self.reportButtonsPanel)
        self.ckb_qtrDrop.setObjectName(u"ckb_qtrDrop")
        self.ckb_qtrDrop.setGeometry(QRect(30, 350, 131, 24))
        self.ckb_qtrFull = QCheckBox(self.reportButtonsPanel)
        self.ckb_qtrFull.setObjectName(u"ckb_qtrFull")
        self.ckb_qtrFull.setGeometry(QRect(30, 390, 121, 24))
        self.ckb_skunk = QCheckBox(self.reportButtonsPanel)
        self.ckb_skunk.setObjectName(u"ckb_skunk")
        self.ckb_skunk.setGeometry(QRect(30, 430, 121, 24))
        self.ckb_tourney = QCheckBox(self.reportButtonsPanel)
        self.ckb_tourney.setObjectName(u"ckb_tourney")
        self.ckb_tourney.setGeometry(QRect(30, 470, 131, 24))
        self.pb_runReportsButton = QPushButton(self.reportButtonsPanel)
        self.pb_runReportsButton.setObjectName(u"pb_runReportsButton")
        self.pb_runReportsButton.setGeometry(QRect(20, 510, 191, 71))
        font4 = QFont()
        font4.setPointSize(14)
        font4.setWeight(QFont.Medium)
        self.pb_runReportsButton.setFont(font4)
        self.pb_runReportsButton.setFlat(False)
        self.label_36 = QLabel(self.reportsTab)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(30, -2, 71, 20))
        self.label_36.setAutoFillBackground(True)
        self.label_36.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_37 = QLabel(self.reportsTab)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(230, 0, 63, 20))
        self.label_37.setAutoFillBackground(True)
        self.label_37.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.tabWidget.addTab(self.reportsTab, "")
        MainCribbageWindow.setCentralWidget(self.TopContainer)
        self.tabWidget.raise_()
        self.sessionPanel.raise_()
        self.SessionFrameLabel.raise_()
        QWidget.setTabOrder(self.le_resultLinePlayerGw, self.le_resultLinePlayerSprd)
        QWidget.setTabOrder(self.le_resultLinePlayerSprd, self.le_resultLinePlayerTkn)
        QWidget.setTabOrder(self.le_resultLinePlayerTkn, self.le_resultLinePlayerCash)
        QWidget.setTabOrder(self.le_resultLinePlayerCash, self.le_streetEntry)
        QWidget.setTabOrder(self.le_streetEntry, self.le_cityEntry)
        QWidget.setTabOrder(self.le_cityEntry, self.le_stateEntry)
        QWidget.setTabOrder(self.le_stateEntry, self.le_zipEntry)
        QWidget.setTabOrder(self.le_zipEntry, self.le_phoneEntry)
        QWidget.setTabOrder(self.le_phoneEntry, self.le_emailEntry)
        QWidget.setTabOrder(self.le_emailEntry, self.le_accNumberEntry)
        QWidget.setTabOrder(self.le_accNumberEntry, self.le_expiresEntry)
        QWidget.setTabOrder(self.le_expiresEntry, self.le_joinedEntry)
        QWidget.setTabOrder(self.le_joinedEntry, self.le_activeEntry)
        QWidget.setTabOrder(self.le_activeEntry, self.le_tourneyNumberEntry)
        QWidget.setTabOrder(self.le_tourneyNumberEntry, self.le_tourneyDateEntry)
        QWidget.setTabOrder(self.le_tourneyDateEntry, self.lw_listOfTourneys)
        QWidget.setTabOrder(self.lw_listOfTourneys, self.lw_listOfResultPlayers)
        QWidget.setTabOrder(self.lw_listOfResultPlayers, self.showAllPlayers)
        QWidget.setTabOrder(self.showAllPlayers, self.listOfPlayers)
        QWidget.setTabOrder(self.listOfPlayers, self.le_firstNameEntry)
        QWidget.setTabOrder(self.le_firstNameEntry, self.le_lastNameEntry)
        QWidget.setTabOrder(self.le_lastNameEntry, self.lw_listOfResultsNames)
        QWidget.setTabOrder(self.lw_listOfResultsNames, self.ckb_allReports)
        QWidget.setTabOrder(self.ckb_allReports, self.ckb_alpha)
        QWidget.setTabOrder(self.ckb_alpha, self.ckb_battingAverage)
        QWidget.setTabOrder(self.ckb_battingAverage, self.ckb_cash)
        QWidget.setTabOrder(self.ckb_cash, self.ckb_individStats)
        QWidget.setTabOrder(self.ckb_individStats, self.ckb_nationalAvges)
        QWidget.setTabOrder(self.ckb_nationalAvges, self.ckb_qtrDrop)
        QWidget.setTabOrder(self.ckb_qtrDrop, self.ckb_skunk)
        QWidget.setTabOrder(self.ckb_skunk, self.ckb_tourney)
        QWidget.setTabOrder(self.ckb_tourney, self.pb_runReportsButton)
        QWidget.setTabOrder(self.pb_runReportsButton, self.lw_listOfResultsGw)
        QWidget.setTabOrder(self.lw_listOfResultsGw, self.lw_listOfResultsSprd)
        QWidget.setTabOrder(self.lw_listOfResultsSprd, self.tabWidget)
        QWidget.setTabOrder(self.tabWidget, self.lw_listOfResultsGp)
        QWidget.setTabOrder(self.lw_listOfResultsGp, self.lw_listOfResultsGvn)
        QWidget.setTabOrder(self.lw_listOfResultsGvn, self.lw_listOfPlayersPoints)
        QWidget.setTabOrder(self.lw_listOfPlayersPoints, self.lw_listOfResultsTkn)
        QWidget.setTabOrder(self.lw_listOfResultsTkn, self.ckb_qtrFull)
        QWidget.setTabOrder(self.ckb_qtrFull, self.lw_listOfResultsOrder)
        QWidget.setTabOrder(self.lw_listOfResultsOrder, self.lw_listOfResultsCash)
        QWidget.setTabOrder(self.lw_listOfResultsCash, self.tourneysTabPanel)
        QWidget.setTabOrder(self.tourneysTabPanel, self.lw_listOfReportTourneys)
        QWidget.setTabOrder(self.lw_listOfReportTourneys, self.TourneysFrame)
        QWidget.setTabOrder(self.TourneysFrame, self.ExistingTourneysPanel)

        self.retranslateUi(MainCribbageWindow)

        self.stackedActivityWidget.setCurrentIndex(3)
        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainCribbageWindow)
    # setupUi

    def retranslateUi(self, MainCribbageWindow):
        MainCribbageWindow.setWindowTitle(QCoreApplication.translate("MainCribbageWindow", u"Cribbage Grass Roots", None))
        self.label_8.setText(QCoreApplication.translate("MainCribbageWindow", u"Club No:", None))
        self.label_17.setText(QCoreApplication.translate("MainCribbageWindow", u"Active:", None))
        self.label_18.setText(QCoreApplication.translate("MainCribbageWindow", u"Name:", None))
        self.label_19.setText(QCoreApplication.translate("MainCribbageWindow", u"Season:", None))
        self.hdrClubNumber.setText(QCoreApplication.translate("MainCribbageWindow", u"100", None))
        self.hdrClubName.setText(QCoreApplication.translate("MainCribbageWindow", u"Century Peggers", None))
        self.hdrActivePlayerCount.setText(QCoreApplication.translate("MainCribbageWindow", u"30", None))
        self.hdrSeason.setText(QCoreApplication.translate("MainCribbageWindow", u"2024-25", None))
        self.clubFrameLabel.setText(QCoreApplication.translate("MainCribbageWindow", u"Club", None))
        self.activityFrameLabel.setText(QCoreApplication.translate("MainCribbageWindow", u"Activity", None))
        self.SessionFrameLabel.setText(QCoreApplication.translate("MainCribbageWindow", u"Session", None))
        self.lb_newPlayerLabel.setText(QCoreApplication.translate("MainCribbageWindow", u"New Player", None))
        self.firstNameLabel.setText(QCoreApplication.translate("MainCribbageWindow", u"First Name", None))
        self.lastNameLabel.setText(QCoreApplication.translate("MainCribbageWindow", u"Last Name", None))
        self.streetLabel.setText(QCoreApplication.translate("MainCribbageWindow", u"Street", None))
        self.cityLabel.setText(QCoreApplication.translate("MainCribbageWindow", u"City", None))
        self.stateLabel.setText(QCoreApplication.translate("MainCribbageWindow", u"State", None))
        self.zipLabel.setText(QCoreApplication.translate("MainCribbageWindow", u"Zip", None))
        self.phoneLabel.setText(QCoreApplication.translate("MainCribbageWindow", u"Phone", None))
        self.emailLabel.setText(QCoreApplication.translate("MainCribbageWindow", u"Email", None))
        self.accNumberLabel.setText(QCoreApplication.translate("MainCribbageWindow", u"ACC Number", None))
        self.expiresLabel.setText(QCoreApplication.translate("MainCribbageWindow", u"Expires", None))
        self.joinedLabel.setText(QCoreApplication.translate("MainCribbageWindow", u"Joined", None))
        self.activeLabel.setText(QCoreApplication.translate("MainCribbageWindow", u"Active", None))
        self.label.setText(QCoreApplication.translate("MainCribbageWindow", u"(0 or 1)", None))
        self.existingPlayersLabel.setText(QCoreApplication.translate("MainCribbageWindow", u"Existing Players", None))
        self.activePlayerLabel.setText(QCoreApplication.translate("MainCribbageWindow", u"* = Active", None))
        self.showAllPlayers.setText(QCoreApplication.translate("MainCribbageWindow", u"Show All", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.playersTab), QCoreApplication.translate("MainCribbageWindow", u"Players", None))
        self.tourneyF6EnterResultsLabel.setText(QCoreApplication.translate("MainCribbageWindow", u"F6 - Enter results for selected tourney", None))
        self.trnyNoHdr.setText(QCoreApplication.translate("MainCribbageWindow", u"Trny No.", None))
        self.trnyDataHdr.setText(QCoreApplication.translate("MainCribbageWindow", u"Data", None))
        self.trnyDateHdr.setText(QCoreApplication.translate("MainCribbageWindow", u"Trny Date", None))
        self.label_4.setText(QCoreApplication.translate("MainCribbageWindow", u"Existing Tournaments", None))
        self.lb_tourneyNumberLabel.setText(QCoreApplication.translate("MainCribbageWindow", u"Tourney Number", None))
        self.lb_tourneyDateLabel.setText(QCoreApplication.translate("MainCribbageWindow", u"Tourney Date", None))
        self.newTourneyFrameLabel.setText(QCoreApplication.translate("MainCribbageWindow", u"New Tourney", None))
        self.lb_badNumber.setText(QCoreApplication.translate("MainCribbageWindow", u"Bad Number:       Tourney number not a number", None))
        self.lb_tourneyOutofRange.setText(QCoreApplication.translate("MainCribbageWindow", u"Out of Range:       Number must be from 1 - 65", None))
        self.lb_duplicateTourneyNumber.setText(QCoreApplication.translate("MainCribbageWindow", u"Duplicate Tourney Number:       ", None))
        self.lb_badDateFormat.setText(QCoreApplication.translate("MainCribbageWindow", u"Bad Date Format:  ", None))
        self.lb_duplicateTourneyDate.setText(QCoreApplication.translate("MainCribbageWindow", u"Duplicate Date:", None))
        self.label_2.setText(QCoreApplication.translate("MainCribbageWindow", u"Tourneys", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tourneysTab), QCoreApplication.translate("MainCribbageWindow", u"Tourneys", None))
        self.label_9.setText(QCoreApplication.translate("MainCribbageWindow", u"Tourney Date", None))
        self.label_10.setText(QCoreApplication.translate("MainCribbageWindow", u"Tourney No.", None))
        self.label_11.setText(QCoreApplication.translate("MainCribbageWindow", u"Count", None))
        self.lb_tourneyHdrDate.setText("")
        self.lb_tourneyHdrNumber.setText("")
        self.lb_tourneyHdrCount.setText("")
        self.label_12.setText(QCoreApplication.translate("MainCribbageWindow", u"Spread", None))
        self.label_13.setText(QCoreApplication.translate("MainCribbageWindow", u"Skunks", None))
        self.label_14.setText(QCoreApplication.translate("MainCribbageWindow", u"Plus", None))
        self.label_15.setText(QCoreApplication.translate("MainCribbageWindow", u"Minus", None))
        self.label_16.setText(QCoreApplication.translate("MainCribbageWindow", u"Diff", None))
        self.lb_spreadPlusValue.setText("")
        self.lb_spreadMinusValue.setText("")
        self.lb_spreadDiffValue.setText("")
        self.lb_skunkPlusValue.setText("")
        self.lb_skunkMinusValue.setText("")
        self.lb_skunkDiffValue.setText("")
        self.label_7.setText(QCoreApplication.translate("MainCribbageWindow", u"Points", None))
        self.listOfPlayerNames.setText(QCoreApplication.translate("MainCribbageWindow", u"Player Name", None))
        self.label_23.setText(QCoreApplication.translate("MainCribbageWindow", u"Names", None))
        self.label_24.setText(QCoreApplication.translate("MainCribbageWindow", u"Gp", None))
        self.label_25.setText(QCoreApplication.translate("MainCribbageWindow", u"Gw", None))
        self.label_26.setText(QCoreApplication.translate("MainCribbageWindow", u"Sprd", None))
        self.label_27.setText(QCoreApplication.translate("MainCribbageWindow", u"Tkn", None))
        self.label_28.setText(QCoreApplication.translate("MainCribbageWindow", u"Order", None))
        self.label_29.setText(QCoreApplication.translate("MainCribbageWindow", u"Gvn", None))
        self.label_31.setText(QCoreApplication.translate("MainCribbageWindow", u"$'s", None))
        self.label_5.setText(QCoreApplication.translate("MainCribbageWindow", u"Selected Players", None))
        self.label_6.setText(QCoreApplication.translate("MainCribbageWindow", u"Tourney Results", None))
        self.label_41.setText(QCoreApplication.translate("MainCribbageWindow", u"Name", None))
        self.label_42.setText(QCoreApplication.translate("MainCribbageWindow", u"Gp", None))
        self.label_43.setText(QCoreApplication.translate("MainCribbageWindow", u"Gw", None))
        self.label_44.setText(QCoreApplication.translate("MainCribbageWindow", u"Sprd", None))
        self.label_45.setText(QCoreApplication.translate("MainCribbageWindow", u"Tkn", None))
        self.label_46.setText(QCoreApplication.translate("MainCribbageWindow", u"$'s", None))
        self.label_47.setText(QCoreApplication.translate("MainCribbageWindow", u"Gvn", None))
        self.label_40.setText("")
        self.lb_resultLinePlayerName.setText("")
        self.lb_resultLinePlayerGvn.setText("")
        self.label_3.setText(QCoreApplication.translate("MainCribbageWindow", u"Results Panel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.resultsTab), QCoreApplication.translate("MainCribbageWindow", u"Results", None))
        self.ckb_allReports.setText(QCoreApplication.translate("MainCribbageWindow", u"All Reports", None))
        self.ckb_alpha.setText(QCoreApplication.translate("MainCribbageWindow", u"Alpha Report", None))
        self.ckb_battingAverage.setText(QCoreApplication.translate("MainCribbageWindow", u"Batting Average Report", None))
        self.ckb_cash.setText(QCoreApplication.translate("MainCribbageWindow", u"Cash Report", None))
        self.ckb_individStats.setText(QCoreApplication.translate("MainCribbageWindow", u"Individ. Stats Report", None))
        self.ckb_nationalAvges.setText(QCoreApplication.translate("MainCribbageWindow", u"National Avges Reports", None))
        self.ckb_qtrDrop.setText(QCoreApplication.translate("MainCribbageWindow", u"Qtr Drop Report", None))
        self.ckb_qtrFull.setText(QCoreApplication.translate("MainCribbageWindow", u"Qtr Full Report", None))
        self.ckb_skunk.setText(QCoreApplication.translate("MainCribbageWindow", u"Skunk Report", None))
        self.ckb_tourney.setText(QCoreApplication.translate("MainCribbageWindow", u"Tourney Report", None))
        self.pb_runReportsButton.setText(QCoreApplication.translate("MainCribbageWindow", u"Run Selected Reports", None))
        self.label_36.setText(QCoreApplication.translate("MainCribbageWindow", u"Tourneys", None))
        self.label_37.setText(QCoreApplication.translate("MainCribbageWindow", u"Reports", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.reportsTab), QCoreApplication.translate("MainCribbageWindow", u"Reports", None))
    # retranslateUi

