# Form implementation generated from reading ui file 'tourneysActivityPanel.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_tourneysactivitypanel(object):
    def setupUi(self, tourneysactivitypanel):
        tourneysactivitypanel.setObjectName("tourneysactivitypanel")
        tourneysactivitypanel.resize(711, 161)
        self.tourneysactivitywidget = QtWidgets.QWidget(parent=tourneysactivitypanel)
        self.tourneysactivitywidget.setGeometry(QtCore.QRect(0, 10, 711, 161))
        self.tourneysactivitywidget.setObjectName("tourneysactivitywidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.tourneysactivitywidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 0, 291, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.playersF1ActivityLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.playersF1ActivityLabel.setObjectName("playersF1ActivityLabel")
        self.verticalLayout_9.addWidget(self.playersF1ActivityLabel)
        self.playersF2ActivityLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.playersF2ActivityLabel.setObjectName("playersF2ActivityLabel")
        self.verticalLayout_9.addWidget(self.playersF2ActivityLabel)
        self.playersF3ActivityLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.playersF3ActivityLabel.setObjectName("playersF3ActivityLabel")
        self.verticalLayout_9.addWidget(self.playersF3ActivityLabel)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.tourneysactivitywidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(360, 0, 331, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.playersF9ActivityLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.playersF9ActivityLabel.setObjectName("playersF9ActivityLabel")
        self.verticalLayout.addWidget(self.playersF9ActivityLabel)
        self.playersF10ActivityLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.playersF10ActivityLabel.setObjectName("playersF10ActivityLabel")
        self.verticalLayout.addWidget(self.playersF10ActivityLabel)
        self.playersEscActivityLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.playersEscActivityLabel.setObjectName("playersEscActivityLabel")
        self.verticalLayout.addWidget(self.playersEscActivityLabel)

        self.retranslateUi(tourneysactivitypanel)
        QtCore.QMetaObject.connectSlotsByName(tourneysactivitypanel)

    def retranslateUi(self, tourneysactivitypanel):
        _translate = QtCore.QCoreApplication.translate
        tourneysactivitypanel.setWindowTitle(_translate("tourneysactivitypanel", "Form"))
        self.playersF1ActivityLabel.setText(_translate("tourneysactivitypanel", "F1    Get help with this activity"))
        self.playersF2ActivityLabel.setText(_translate("tourneysactivitypanel", "F2    Edit Currently Selected Tourney"))
        self.playersF3ActivityLabel.setText(_translate("tourneysactivitypanel", "F3    Create new tourney"))
        self.playersF9ActivityLabel.setText(_translate("tourneysactivitypanel", "F9    Delete selected tourney"))
        self.playersF10ActivityLabel.setText(_translate("tourneysactivitypanel", "F10  Save updates"))
        self.playersEscActivityLabel.setText(_translate("tourneysactivitypanel", "Esc   Quit current activity"))
